[package]
name = "gm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
camino = "1.1.9"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
gix = "0.66.0"
itertools = "0.13.0"
tracing = "0.1.40"
which = "6.0.3"
